name: AI PR Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  ai-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get PR diff
        id: diff
        run: |
          # Get the diff between base and head
          git fetch origin ${{ github.event.pull_request.base.ref }}
          DIFF=$(git diff origin/${{ github.event.pull_request.base.ref }}...${{ github.sha }})
          
          # Save diff to file to handle multiline
          echo "$DIFF" > pr-diff.txt
          
          # Get PR info
          echo "pr_number=${{ github.event.pull_request.number }}" >> $GITHUB_OUTPUT
          echo "pr_title=${{ github.event.pull_request.title }}" >> $GITHUB_OUTPUT
          echo "pr_author=${{ github.event.pull_request.user.login }}" >> $GITHUB_OUTPUT

      - name: Call Review API
        id: review
        env:
          VERCEL_URL: ${{ secrets.VERCEL_URL }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          DIFF_CONTENT=$(cat pr-diff.txt)
          
          RESPONSE=$(curl -X POST "$VERCEL_URL/api/review-pr" \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -d @- <<EOF
          {
            "diff": $(echo "$DIFF_CONTENT" | jq -Rs .),
            "prNumber": ${{ steps.diff.outputs.pr_number }},
            "prTitle": $(echo "${{ steps.diff.outputs.pr_title }}" | jq -Rs .),
            "prAuthor": "${{ steps.diff.outputs.pr_author }}",
            "repository": "${{ github.repository }}"
          }
          EOF
          )
          
          echo "response=$RESPONSE" >> $GITHUB_OUTPUT

      - name: Comment on PR
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const response = JSON.parse('${{ steps.review.outputs.response }}');
            
            // Format the review comment
            let comment = `## 🤖 Revisão Automatizada de PR\n\n`;
            comment += `### Status: ${response.status === 'approved' ? '✅ Aprovado' : response.status === 'changes_requested' ? '⚠️ Mudanças Solicitadas' : '❌ Reprovado'}\n\n`;
            comment += `**Resumo:** ${response.summary}\n\n`;
            
            if (response.issues && response.issues.length > 0) {
              comment += `### 🔍 Problemas Encontrados\n\n`;
              response.issues.forEach((issue, index) => {
                const icon = issue.severity === 'high' ? '🔴' : issue.severity === 'medium' ? '🟡' : '🟢';
                comment += `${index + 1}. ${icon} **${issue.type}** (Severidade: ${issue.severity})\n`;
                comment += `   - **Descrição:** ${issue.description}\n`;
                if (issue.file) comment += `   - **Arquivo:** \`${issue.file}\`\n`;
                if (issue.line) comment += `   - **Linha:** ${issue.line}\n`;
                if (issue.suggestion) comment += `   - **Sugestão:** ${issue.suggestion}\n`;
                comment += `\n`;
              });
            }
            
            if (response.recommendations && response.recommendations.length > 0) {
              comment += `### 💡 Recomendações\n\n`;
              response.recommendations.forEach((rec, index) => {
                comment += `${index + 1}. ${rec}\n`;
              });
            }
            
            comment += `\n---\n*Revisão gerada automaticamente por AI • [Ver Dashboard](${process.env.VERCEL_URL})*`;
            
            // Post comment
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: comment
            });
